name: Build/Publish Image

on:
  push:
    paths:
      - 'requirements.txt'
      - 'Dockerfile-alpine'
      - 'Dockerfile-debian'
      - 'redbot.sh'
  pull_request:
    paths:
      - 'requirements.txt'
      - 'Dockerfile-alpine'
      - 'Dockerfile-debian'
      - 'redbot.sh'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.base }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: debian
            tag: latest
            extra_tag: ''
          - base: alpine
            tag: alpine
            extra_tag: -alpine
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Red version
      run: echo "RED_VERSION=$(cat ./requirements.txt | grep 'Red-DiscordBot' | sed 's/Red-DiscordBot == //g')" >> $GITHUB_ENV

    - name: Build image
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-${{ matrix.base }}
        tags: |
          rhomelab/red-discordbot:${{ matrix.tag }}
          rhomelab/red-discordbot:${{ env.RED_VERSION }}${{ matrix.extra_tag }}
          ghcr.io/rhomelab/red-discordbot:${{ matrix.tag }}
          ghcr.io/rhomelab/red-discordbot:${{ env.RED_VERSION }}${{ matrix.extra_tag }}

    - name: Publish image
      if: github.event_name == 'push'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-${{ matrix.base }}
        push: true
        tags: |
          rhomelab/red-discordbot:${{ matrix.tag }}
          rhomelab/red-discordbot:${{ env.RED_VERSION }}${{ matrix.extra_tag }}
          ghcr.io/rhomelab/red-discordbot:${{ matrix.tag }}
          ghcr.io/rhomelab/red-discordbot:${{ env.RED_VERSION }}${{ matrix.extra_tag }}

    - name: Image digest
      if: github.event_name == 'push'
      run: echo ${{ steps.docker_build.outputs.digest }}
