name: Build/Publish Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image [true|false]'
        required: false
        default: 'false'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      red-version: ${{ steps.red-version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Red version
      id: red-version
      run: |
        RED_VERSION=$(cat ./requirements.txt | grep 'Red-DiscordBot' | sed 's/Red-DiscordBot == //g')
        echo "::set-output name=version::$RED_VERSION"

  build:
    name: Build ${{ matrix.base }} image
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: debian
            tag: latest
            extra_tag: ''
          - base: alpine
            tag: alpine
            extra_tag: -alpine
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile-${{ matrix.base }}
        push: ${{ github.event_name != 'pull_request' || github.event.inputs.push == 'true' }}
        tags: |
          rhomelab/red-discordbot:${{ matrix.tag }}
          rhomelab/red-discordbot:${{ needs.setup.outputs.red-version }}${{ matrix.extra_tag }}
          ghcr.io/rhomelab/red-discordbot:${{ matrix.tag }}
          ghcr.io/rhomelab/red-discordbot:${{ needs.setup.outputs.red-version }}${{ matrix.extra_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Image digest
      if: github.event_name != 'pull_request'
      run: echo ${{ steps.docker_build.outputs.digest }}
