name: Build Alpine Image

on:
  pull_request:
    paths:
      - 'requirements.txt'
      - 'Dockerfile-alpine'
      - 'redbot.sh'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Red version
      run: echo "RED_VERSION=$(cat ./requirements.txt | grep 'Red-DiscordBot' | sed 's/Red-DiscordBot == //g')" >> $GITHUB_ENV

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-alpine
        tags: |
          red-discordbot:alpine
          red-discordbot:${{ env.RED_VERSION }}-alpine
