name: 'Cleanup PR images'

on:
  pull_request:
    types: [closed]

jobs:
  purge-image:
    name: Delete ${{ matrix.tag }} image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: rhomelab
          name: red-discordbot
          token: ${{ secrets.IMAGE_CLEANUP_PAT }}
          tag: pr-${{ github.event.pull_request.number }}
