name: Build & Publish Alpine Image

on:
  push:
    paths:
      - 'requirements.txt'
      - 'Dockerfile-alpine'
      - 'redbot.sh'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Red version
      run: echo "RED_VERSION=$(cat ./requirements.txt | grep 'Red-DiscordBot' | sed 's/Red-DiscordBot == //g')" >> $GITHUB_ENV

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-alpine
        push: true
        tags: |
          rhomelab/red-discordbot:alpine
          rhomelab/red-discordbot:${{ env.RED_VERSION }}-alpine
          ghcr.io/rhomelab/red-discordbot:alpine
          ghcr.io/rhomelab/red-discordbot:${{ env.RED_VERSION }}-alpine

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
